import Link from "next/link";
import {
  FaArrowLeft,
  FaBrain,
  FaBroadcastTower,
  FaCode,
  FaImage,
  FaLaptopCode,
  FaUniversity,
  FaWaveSquare,
} from "react-icons/fa";
import { FaLocationDot } from "react-icons/fa6";
import { FaLocationArrow } from "react-icons/fa6";
const researchAreas = [
  {
    title: "Electromagnetic Emanation Analysis",
    description:
      "Studied electromagnetic emissions produced by HDMI cables and their relationship to the visual content displayed on a monitor.",
    icon: FaBroadcastTower,
  },
  {
    title: "Software Defined Radio",
    description:
      "Used SDR-based signal acquisition concepts and the GNU Radio framework to process and reconstruct digital signals.",
    icon: FaWaveSquare,
  },
  {
    title: "Inverse Problem Formulation",
    description:
      "Modeled image recovery from noisy electromagnetic measurements as an inverse reconstruction problem.",
    icon: FaBrain,
  },
  {
    title: "Deep Learning Reconstruction",
    description:
      "Explored deep-learning methods for recovering displayed images from distorted and incomplete signal observations.",
    icon: FaImage,
  },
  {
    title: "HDMI Signal Analysis",
    description:
      "Investigated the challenges introduced by 10-bit HDMI encoding and non-linear relationships between signal values and pixel intensities.",
    icon: FaCode,
  },
  {
    title: "Synthetic Data Generation",
    description:
      "Developed a mathematically guided approach for generating synthetic training data before relying on complex real-world capture equipment.",
    icon: FaLaptopCode,
  },
];

const contributions = [
  "Replicated a research system for recovering displayed images from electromagnetic emissions generated by HDMI cables.",
  "Studied TEMPEST-style electromagnetic side-channel attacks and their application to visual information leakage.",
  "Worked with Software Defined Radio concepts and GNU Radio-based digital signal processing workflows.",
  "Analyzed the effect of 10-bit HDMI encoding on signal reconstruction and pixel-intensity estimation.",
  "Formulated the eavesdropping process as an inverse problem suitable for deep-learning-based reconstruction.",
  "Designed a synthetic-data training methodology using mathematical signal models.",
  "Reduced the initial dependency on real-world electromagnetic capture setups by creating controlled training samples.",
];

const workflow = [
  {
    number: "01",
    title: "Signal Modeling",
    description:
      "Analyze how HDMI transmission signals and electromagnetic leakage relate to the original displayed image.",
  },
  {
    number: "02",
    title: "Synthetic Data Generation",
    description:
      "Use mathematical signal analysis to generate paired signal and image samples for model development.",
  },
  {
    number: "03",
    title: "Signal Processing",
    description:
      "Process the generated or captured signals using SDR concepts, filtering, synchronization, and GNU Radio workflows.",
  },
  {
    number: "04",
    title: "Inverse Reconstruction",
    description:
      "Train a deep-learning model to estimate the original image from incomplete and distorted electromagnetic observations.",
  },
  {
    number: "05",
    title: "Evaluation",
    description:
      "Compare reconstructed images with their original references and identify limitations in signal quality and encoding.",
  },
];

const technologies = [
  "Python",
  "GNU Radio",
  "Software Defined Radio",
  "Digital Signal Processing",
  "Deep Learning",
  "Inverse Problems",
  "Synthetic Data",
  "HDMI Signal Analysis",
  "Electromagnetic Side Channels",
  "Image Reconstruction",
  "TEMPEST",
  "Mathematical Modeling",
];

const ResearchInternshipPage = () => {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#000319] px-6 py-24 text-white sm:px-10">
      <div className="pointer-events-none absolute left-1/2 top-0 h-[550px] w-[550px] -translate-x-1/2 rounded-full bg-purple-600/15 blur-[170px]" />

      <div className="pointer-events-none absolute right-0 top-[700px] h-[400px] w-[400px] rounded-full bg-blue-600/10 blur-[160px]" />

      <section className="relative z-10 mx-auto max-w-6xl">
        <a
            href="/#projects"
            className="inline-flex items-center gap-3 rounded-full bg-purple-500 px-6 py-3 font-semibold text-white transition duration-300 hover:-translate-y-1 hover:bg-purple-600"
        >
            Back to Projects
            <FaLocationArrow />
        /a>

        <div className="mb-14">
          <p className="mb-4 text-sm font-semibold uppercase tracking-[0.25em] text-purple-400">
            Research Internship | June 2025 – July 2025
          </p>

          <h1 className="mb-6 max-w-5xl text-4xl font-bold leading-tight md:text-6xl">
            Electromagnetic Image Reconstruction Using{" "}
            <span className="text-purple-400">
              SDR, GNU Radio, and Deep Learning
            </span>
          </h1>

          <p className="mb-8 max-w-4xl text-lg leading-8 text-white/65 md:text-xl">
            A research project focused on recovering displayed images from
            electromagnetic emissions produced by HDMI cables through digital
            signal processing, inverse-problem formulation, and deep-learning
            reconstruction.
          </p>

          <div className="flex flex-wrap gap-4">
            <div className="inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm text-white/75">
              <FaUniversity className="text-purple-400" />
              6G Research Center, Khalifa University
            </div>

            <div className="inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/[0.04] px-5 py-3 text-sm text-white/75">
              <FaLocationDot className="text-purple-400" />
              Abu Dhabi, UAE
            </div>
          </div>
        </div>

        <div className="mb-14 overflow-hidden rounded-3xl border border-white/10 bg-white/[0.04] p-4 shadow-2xl shadow-purple-950/30">
          <div className="relative flex min-h-[320px] items-center justify-center overflow-hidden rounded-2xl bg-[#070a20] px-8 py-16 text-center md:min-h-[440px]">
            <div className="absolute inset-0 bg-[linear-gradient(to_right,rgba(255,255,255,0.04)_1px,transparent_1px),linear-gradient(to_bottom,rgba(255,255,255,0.04)_1px,transparent_1px)] bg-[size:40px_40px]" />

            <div className="absolute left-1/2 top-1/2 h-56 w-56 -translate-x-1/2 -translate-y-1/2 rounded-full bg-purple-600/20 blur-[100px]" />

            <div className="relative z-10">
              <FaBroadcastTower className="mx-auto mb-6 text-6xl text-purple-400" />

              <h2 className="mb-4 text-2xl font-bold md:text-4xl">
                Electromagnetic Side-Channel Image Recovery
              </h2>

              <p className="mx-auto max-w-2xl leading-7 text-white/55">
                Reconstructing visual information from unintended HDMI cable
                emissions using signal processing and machine learning.
              </p>
            </div>
          </div>
        </div>

        <div className="mb-14 grid gap-6 md:grid-cols-3">
          <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 transition duration-300 hover:-translate-y-1 hover:border-purple-500/50">
            <p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-purple-400">
              Organization
            </p>
            <h3 className="mb-2 text-xl font-bold">Khalifa University</h3>
            <p className="leading-7 text-white/60">6G Research Center</p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 transition duration-300 hover:-translate-y-1 hover:border-purple-500/50">
            <p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-purple-400">
              Position
            </p>
            <h3 className="mb-2 text-xl font-bold">Research Intern</h3>
            <p className="leading-7 text-white/60">
              Signal Processing and Deep Learning
            </p>
          </article>

          <article className="rounded-2xl border border-white/10 bg-white/[0.04] p-6 transition duration-300 hover:-translate-y-1 hover:border-purple-500/50">
            <p className="mb-2 text-xs font-semibold uppercase tracking-[0.2em] text-purple-400">
              Duration
            </p>
            <h3 className="mb-2 text-xl font-bold">Two Months</h3>
            <p className="leading-7 text-white/60">June 2025 – July 2025</p>
          </article>
        </div>

        <section className="mb-10 rounded-3xl border border-white/10 bg-white/[0.04] p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Research overview
          </p>

          <h2 className="mb-5 text-3xl font-bold">Project Overview</h2>

          <div className="space-y-5 text-lg leading-8 text-white/65">
            <p>
              This research internship focused on replicating a system capable
              of reconstructing displayed images from unintended electromagnetic
              emissions produced by HDMI cables. This form of information
              leakage is associated with TEMPEST-style electromagnetic
              side-channel attacks.
            </p>

            <p>
              The project investigated how radiated signals could be processed
              through Software Defined Radio and GNU Radio workflows and then
              transformed into meaningful visual information.
            </p>

            <p>
              Because HDMI uses 10-bit encoding and introduces a non-linear
              relationship between transmitted signals and visible pixel
              intensities, direct image recovery is difficult. The
              reconstruction process was therefore formulated as an inverse
              problem and approached using deep learning.
            </p>
          </div>
        </section>

        <section className="mb-10 rounded-3xl border border-white/10 bg-[#070a20] p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Technical challenge
          </p>

          <h2 className="mb-5 text-3xl font-bold">
            Recovering Images from Noisy Electromagnetic Signals
          </h2>

          <div className="grid gap-8 md:grid-cols-2">
            <div>
              <h3 className="mb-3 text-xl font-semibold text-purple-300">
                HDMI Encoding Complexity
              </h3>

              <p className="leading-8 text-white/60">
                HDMI signals are digitally encoded, meaning the measured
                electromagnetic waveform does not directly correspond to the
                brightness or color of each displayed pixel. The 10-bit encoded
                signal creates a non-linear mapping that makes conventional
                signal-to-image conversion unreliable.
              </p>
            </div>

            <div>
              <h3 className="mb-3 text-xl font-semibold text-purple-300">
                Inverse Reconstruction
              </h3>

              <p className="leading-8 text-white/60">
                Rather than explicitly reversing every stage of the transmission
                process, the problem was treated as an inverse learning task. A
                model learns to estimate the original visual content from
                distorted signal observations.
              </p>
            </div>
          </div>
        </section>

        <section className="mb-10">
          <div className="mb-10">
            <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
              Research areas
            </p>

            <h2 className="text-3xl font-bold md:text-4xl">
              Core Technical Components
            </h2>
          </div>

          <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
            {researchAreas.map((area) => {
              const Icon = area.icon;

              return (
                <article
                  key={area.title}
                  className="rounded-2xl border border-white/10 bg-white/[0.04] p-7 transition duration-300 hover:-translate-y-1 hover:border-purple-500/50 hover:bg-white/[0.07]"
                >
                  <div className="mb-5 flex h-12 w-12 items-center justify-center rounded-xl bg-purple-500/15 text-xl text-purple-400">
                    <Icon />
                  </div>

                  <h3 className="mb-3 text-xl font-semibold">{area.title}</h3>

                  <p className="text-sm leading-7 text-white/60">
                    {area.description}
                  </p>
                </article>
              );
            })}
          </div>
        </section>

        <section className="mb-10 rounded-3xl border border-white/10 bg-white/[0.04] p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Responsibilities
          </p>

          <h2 className="mb-6 text-3xl font-bold">Key Contributions</h2>

          <ul className="space-y-4 text-lg leading-8 text-white/65">
            {contributions.map((contribution) => (
              <li key={contribution} className="flex gap-4">
                <span className="mt-3 h-2 w-2 shrink-0 rounded-full bg-purple-400" />
                <span>{contribution}</span>
              </li>
            ))}
          </ul>
        </section>

        <section className="mb-10 rounded-3xl border border-white/10 bg-[#070a20] p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Research methodology
          </p>

          <h2 className="mb-8 text-3xl font-bold">
            From Signal Modeling to Image Reconstruction
          </h2>

          <div className="space-y-5">
            {workflow.map((step) => (
              <article
                key={step.number}
                className="grid gap-5 rounded-2xl border border-white/10 bg-white/[0.03] p-6 md:grid-cols-[90px_1fr] md:items-center"
              >
                <span className="text-4xl font-bold text-purple-400/50">
                  {step.number}
                </span>

                <div>
                  <h3 className="mb-2 text-xl font-semibold">{step.title}</h3>

                  <p className="leading-7 text-white/60">{step.description}</p>
                </div>
              </article>
            ))}
          </div>
        </section>

        <section className="mb-10 rounded-3xl border border-purple-500/20 bg-gradient-to-br from-purple-500/10 via-white/[0.03] to-transparent p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Training strategy
          </p>

          <h2 className="mb-5 text-3xl font-bold">
            Mathematically Generated Synthetic Data
          </h2>

          <div className="space-y-5 text-lg leading-8 text-white/65">
            <p>
              Collecting real electromagnetic leakage data requires specialized
              radio equipment, carefully controlled display hardware, and a
              repeatable physical capture environment. This makes initial model
              development expensive and time-consuming.
            </p>

            <p>
              To address this limitation, a training methodology was designed
              using mathematical signal analysis. Synthetic electromagnetic
              observations could be generated from known images, creating
              controlled input-output pairs for deep-learning experiments.
            </p>

            <p>
              This approach allowed model architecture, preprocessing methods,
              and reconstruction strategies to be evaluated before introducing
              noise and variability from real-world captures.
            </p>
          </div>
        </section>

        <section className="mb-10 rounded-3xl border border-white/10 bg-white/[0.04] p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Technology stack
          </p>

          <h2 className="mb-6 text-3xl font-bold">Tools and Research Topics</h2>

          <div className="flex flex-wrap gap-3">
            {technologies.map((technology) => (
              <span
                key={technology}
                className="rounded-full border border-purple-500/20 bg-purple-500/10 px-4 py-2 text-sm font-medium text-purple-200 transition hover:border-purple-400/60 hover:bg-purple-500/20"
              >
                {technology}
              </span>
            ))}
          </div>
        </section>

        <section className="rounded-3xl border border-white/10 bg-[#070a20] p-8 shadow-xl shadow-black/20 md:p-10">
          <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
            Research outcome
          </p>

          <h2 className="mb-5 text-3xl font-bold">Learning and Impact</h2>

          <p className="text-lg leading-8 text-white/65">
            The internship provided hands-on experience in electromagnetic
            side-channel research, digital communication signals, Software
            Defined Radio, deep-learning-based inverse problems, and synthetic
            data generation. It also demonstrated how signal processing and
            machine learning can be combined to analyze complex cybersecurity
            and communication-system vulnerabilities.
          </p>
        </section>

        <div className="mt-12">
          <Link
            href="/#experience"
            className="inline-flex items-center gap-3 rounded-full bg-purple-500 px-6 py-3 font-semibold text-white transition duration-300 hover:-translate-y-1 hover:bg-purple-600"
          >
            Back to Experience
            <FaArrowLeft />
          </Link>
        </div>
      </section>
    </main>
  );
};

export default ResearchInternshipPage;
