"use client";

import Link from "next/link";
import {
  FaArrowLeft,
  FaBuilding,
  FaEnvelope,
  FaLinkedin,
  FaLocationDot,
  FaMicrochip,
  FaPhone,
  FaShieldHalved,
  FaTowerBroadcast,
  FaWaveSquare,
} from "react-icons/fa6";
const experiences = [
  {
    id: 1,
    role: "Research Internship",
    organization: "6G Research Center, Khalifa University",
    location: "Abu Dhabi, UAE",
    date: "June 2025 – July 2025",
    type: "Research",
    icon: FaTowerBroadcast,
    details: [
      "Replicated a system for recovering displayed images from electromagnetic emissions generated by HDMI cables as part of TEMPEST-style side-channel research.",
      "Focused on digital signal reconstruction using Software Defined Radio and the GNU Radio framework.",
      "Investigated the challenges introduced by 10-bit encoded HDMI signals and non-linear pixel-intensity mappings.",
      "Formulated the eavesdropping task as an inverse problem and explored deep-learning-based image reconstruction.",
      "Designed a mathematical signal-analysis methodology for generating synthetic training data without initially requiring a real-world capture setup.",
    ],
    technologies: [
      "GNU Radio",
      "Software Defined Radio",
      "Deep Learning",
      "Signal Processing",
      "TEMPEST",
      "Inverse Problems",
      "Synthetic Data",
    ],
    link: "/experience/6g-research-internship",
  },
  {
    id: 2,
    role: "Undergraduate Research",
    organization: "Khalifa University",
    location: "Abu Dhabi, UAE",
    date: "February 2025 – Present",
    type: "Wireless Communications",
    icon: FaWaveSquare,
    details: [
      "Conducted an in-depth literature review on signal processing for relay and cooperative communication protocols.",
      "Analyzed signal-quality requirements for IoT applications, including systems involving dispersed energy sources.",
      "Evaluated the physical-layer security of cooperative wireless transmission systems using amplify-and-forward and decode-and-forward protocols.",
      "Determined quality-of-service and security limits through analytical methods and simulations.",
      "Assessed challenges across different IoT network scenarios and prepared a comprehensive review of system capabilities and limitations.",
      "Currently contributing to an academic paper based on the research.",
    ],
    technologies: [
      "Signal Processing",
      "IoT",
      "Physical Layer Security",
      "Cooperative Communications",
      "Amplify-and-Forward",
      "Decode-and-Forward",
      "Simulation",
    ],
  },
  {
    id: 3,
    role: "Electrical Engineering Intern",
    organization: "ADNOC Offshore, Central Engineering Department",
    location: "Abu Dhabi, UAE",
    date: "Summer 2024",
    type: "Industry Internship",
    icon: FaBuilding,
    details: [
      "Collaborated with electrical engineering supervisors to strengthen understanding of Single Line Diagrams and electrical distribution systems.",
      "Contributed to load-scheduling activities, including electrical-load calculations and equipment-sizing considerations.",
      "Studied Uninterruptible Power Supply systems and their role in maintaining power continuity for critical IT infrastructure.",
      "Worked with switchgear, circuit breakers, and protective relays while learning maintenance and safety-compliance practices.",
      "Participated in discussions with supervisors from multiple departments, including the Arzana Department.",
      "Developed practical exposure to P&IDs, drilling operations, and heat-exchanger systems.",
    ],
    technologies: [
      "Single Line Diagrams",
      "Load Scheduling",
      "Electrical Distribution",
      "UPS",
      "Switchgear",
      "Circuit Breakers",
      "Protective Relays",
      "P&IDs",
    ],
  },
];

const ExperiencePage = () => {
  return (
    <main className="relative min-h-screen overflow-hidden bg-[#000319] px-5 py-24 text-white sm:px-10">
      <div className="pointer-events-none absolute left-1/2 top-0 h-[550px] w-[550px] -translate-x-1/2 rounded-full bg-purple-600/15 blur-[170px]" />

      <div className="pointer-events-none absolute right-0 top-[800px] h-[450px] w-[450px] rounded-full bg-blue-600/10 blur-[170px]" />

      <section className="relative z-10 mx-auto max-w-7xl">
        <Link
          href="/"
          className="mb-10 inline-flex items-center gap-2 text-sm text-white/60 transition hover:text-purple-400"
        >
          <FaArrowLeft />
          Back to home
        </Link>

        <header className="mb-16">
          <p className="mb-4 text-sm font-semibold uppercase tracking-[0.3em] text-purple-400">
            Professional Journey
          </p>
        </header>

        <section>
          <div className="mb-12">
            <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-purple-400">
              Timeline
            </p>

            <h2 className="text-3xl font-bold sm:text-4xl">
              Experience and Research Positions
            </h2>
          </div>

          <div className="relative">
            <div className="absolute bottom-0 left-6 top-0 hidden w-px bg-gradient-to-b from-purple-400 via-blue-500/40 to-transparent md:block" />

            <div className="space-y-10">
              {experiences.map((experience) => {
                const Icon = experience.icon;

                return (
                  <article key={experience.id} className="relative md:pl-20">
                    <div className="absolute left-0 top-8 hidden h-12 w-12 items-center justify-center rounded-full border border-purple-400/40 bg-[#070a20] text-purple-400 shadow-lg shadow-purple-950/30 md:flex">
                      <Icon />
                    </div>

                    <div className="overflow-hidden rounded-3xl border border-white/10 bg-[#070a20] shadow-2xl shadow-black/20 transition duration-300 hover:border-purple-500/40">
                      <div className="border-b border-white/10 bg-white/[0.03] p-7 sm:p-9">
                        <div className="flex flex-col gap-6 lg:flex-row lg:items-start lg:justify-between">
                          <div>
                            <span className="mb-4 inline-flex rounded-full border border-purple-500/20 bg-purple-500/10 px-4 py-2 text-xs font-semibold uppercase tracking-[0.15em] text-purple-300">
                              {experience.type}
                            </span>

                            <h3 className="text-2xl font-bold sm:text-3xl">
                              {experience.role}
                            </h3>

                            <p className="mt-2 text-lg font-medium text-purple-300">
                              {experience.organization}
                            </p>
                          </div>

                          <div className="space-y-2 text-sm text-white/60 lg:text-right">
                            <p className="flex items-center gap-2 lg:justify-end">
                              <FaLocationDot className="text-purple-400" />
                              {experience.location}
                            </p>

                            <p>{experience.date}</p>
                          </div>
                        </div>
                      </div>

                      <div className="p-7 sm:p-9">
                        <ul className="space-y-4 text-base leading-8 text-white/65">
                          {experience.details.map((detail) => (
                            <li key={detail} className="flex gap-4">
                              <span className="mt-3 h-2 w-2 shrink-0 rounded-full bg-purple-400" />
                              <span>{detail}</span>
                            </li>
                          ))}
                        </ul>

                        <div className="mt-8 flex flex-wrap gap-3">
                          {experience.technologies.map((technology) => (
                            <span
                              key={technology}
                              className="rounded-full border border-white/10 bg-white/[0.04] px-4 py-2 text-xs font-medium text-white/70"
                            >
                              {technology}
                            </span>
                          ))}
                        </div>

                        {experience.link && (
                          <Link
                            href={experience.link}
                            className="mt-8 inline-flex items-center gap-3 rounded-full bg-purple-500 px-6 py-3 text-sm font-semibold text-white transition hover:-translate-y-1 hover:bg-purple-600"
                          >
                            View Research Project
                            <FaArrowLeft className="rotate-180" />
                          </Link>
                        )}
                      </div>
                    </div>
                  </article>
                );
              })}
            </div>
          </div>
        </section>

        <div className="mt-12">
          <Link
            href="/"
            className="inline-flex items-center gap-3 rounded-full border border-white/10 bg-white/[0.05] px-6 py-3 font-semibold text-white transition hover:border-purple-400/50 hover:bg-purple-500"
          >
            <FaArrowLeft />
            Back to Home
          </Link>
        </div>
      </section>
    </main>
  );
};

export default ExperiencePage;
